version: '3.8'

services:
  frontend-app:
    image: dummy-frontend
    build:
      context: .
    networks:
      - web-services
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend-nginx-secured.entrypoints=websecure
      - traefik.http.routers.frontend-nginx-secured.rule=Host(`frontend.example.com`)
      - traefik.http.routers.frontend-nginx-secured.tls.certresolver=myresolver

networks:
  web-services:
    external: true
