version: '3.8'

services:
  backend-api:
    image: dummy-backend
    build:
      context: .
    networks:
      - web-services
      - backend-db
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend-api-secured.entrypoints=websecure
      - traefik.http.routers.backend-api-secured.rule=Host(`api.example.com`)
      - traefik.http.routers.backend-api-secured.tls.certresolver=myresolver

networks:
  web-services:
    external: true
  backend-db:
    external: true
