version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.5.3
    restart: always
    ports:
      - '80:80' # http
      - '8080:8080' # Dashboard用
    networks:
      - web-services # Traefik.ymlで指定したネットワーク名であることを確認しておくこと
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # 必須
      - ./config:/etc/traefik/ # 設定ファイルをマウントするため
    depends_on:
      - mongo-db

  # MongoDBはTraefikで管理しない
  mongo-db:
    image: mongo:5.0.3-focal
    container_name: mongo-example
    restart: always
    volumes:
      - mongo-example:/data/db
    environment:
      # ローカルでのテストなのでユーザ名とパスワードは直に書いています
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: mongoPassword
    networks:
      # Traefikで管理しないのでweb-servicesネットワークを指定する必要はない
      - backend-db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoAdmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoPassword
      ME_CONFIG_MONGODB_SERVER: mongo-example
    depends_on:
      - mongo-db
    networks:
      - backend-db

volumes:
  mongo-example:

# 事前にdocker network createで作っておくこと
networks:
  web-services:
    external: true # 他のcomposeファイルでも使うためexternalにしておいた方が便利
  backend-db:
    external: true
