version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.5.3
    restart: always
    ports:
      - '80:80' # http
      - '443:443' # https
    networks:
      - web-services # Traefik.ymlで指定したネットワーク名であることを確認しておくこと
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # 必須
      - ./config:/etc/traefik/ # 設定ファイルをマウントするため
      - ./letsencrypt:/letsencrypt # 自動的にフォルダが作られる。acme.jsonが置かれる
    depends_on:
      - mongo-db

  # MongoDBはTraefikで管理しない
  mongo-db:
    image: mongo:5.0.3-focal
    container_name: mongo-example
    restart: always
    volumes:
      - mongo-example:/data/db
    environment:
      # ローカルでのテストなのでユーザ名とパスワードは直に書いています
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      # Traefikで管理しないのでweb-servicesネットワークを指定する必要はない
      - backend-db

volumes:
  mongo-example:

# 事前にdocker network createで作っておくこと
networks:
  web-services:
    external: true # 他のcomposeファイルでも使うためexternalにしておいた方が便利
  backend-db:
    external: true
