log:
  level: DEBUG

providers:
  docker:
    exposedByDefault: false
    network: web-services

  file:
    directory: /etc/traefik/dynamic

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ':443'

certificatesResolvers:
  myresolver:
    acme:
      email: 'test@test.com' # 自分のメールアドレスを指定
      storage: '/letsencrypt/acme.json' # 認証情報の置き場所を指定。
      tlsChallenge: {} # 「TLS Challenge」を使う。443ポートを開けておく必要がある。
      # Let's Encryptにはレート制限があります。
      # 制限にかからないようにするため、デバッグ時には以下のオプションを追加します。
      # caserver: 'https://acme-staging-v02.api.letsencrypt.org/directory'
